import os
import signal
from typing import Optional
import webbrowser
from contextlib import asynccontextmanager
from random import choices
from string import ascii_lowercase, digits

import requests
from fastapi import FastAPI

# from pydantic import Secret, SecretStr
from prefect.blocks.system import Secret, SecretStr, String
from requests import PreparedRequest

from .models import TL_Auth, TL_Client

REDIRECT_URL = "https://127.0.0.1:8000/oauth"

####################
# Helper functions #
####################


async def get_random_state():
    chars = choices(ascii_lowercase + digits, k=100)
    return "".join(chars)


async def open_authorization_url(state: str):
    """
    Start the authorization flow by redirecting to the Teamleader authorization page
    as described in the [Teamleader documentation](https://developer.teamleader.eu/#/introduction/authentication/authorization-flow)
    """

    req = PreparedRequest()
    req.prepare_url(
        "https://focus.teamleader.eu/oauth2/authorize",
        {
            "client_id": (await String.load("teamleader-client-id")).value,
            "response_type": "code",
            "state": state,
            "redirect_uri": REDIRECT_URL,
        },
    )

    if req.url == None:
        raise ValueError("Could not create authorization url")

    print(f"\nOpen this URL in your webbrowser: \n\n{req.url}\n\n")
    webbrowser.open(req.url)


async def get_access_token_from_teamleader(code: str):
    """
    After the user has granded authorization through the webbrowser, an access code is requested from Teamleader.
    """
    response = requests.post(
        "https://focus.teamleader.eu/oauth2/access_token",
        data={
            "client_id": (await String.load("teamleader-client-id")).value,
            "client_secret": (await Secret.load("teamleader-client-secret")).get(),
            "code": code,
            "grant_type": "authorization_code",
            "redirect_uri": REDIRECT_URL,
        },
    )

    if response.status_code != 200:
        raise RuntimeError(f"Status code {response.status_code} - {response.reason}")

    response = response.json()
    return response


async def save_tokens_to_prefect(auth: TL_Auth):
    """
    Save the access and refresh tokens to Prefect secrets.
    """
    await Secret(value=auth.access_token.get_secret_value()).save(
        name="teamleader-access-token", 
        overwrite=True
    )
    
    await Secret(value=auth.refresh_token.get_secret_value()).save(
        name="teamleader-refresh-token", 
        overwrite=True
    )


def get_auth_tokens_from_prefect(
    tl_auth_uri: str, tl_client: TL_Client
) -> TL_Auth:
    
    try:
        access_token_block = Secret.load("teamleader-access-token")
        refresh_token_block = Secret.load("teamleader-refresh-token")
    except ValueError as e:
        raise KeyError(
            "Missing authorization data in Prefect blocks. Are 'teamleader-access-token' and 'teamleader-refresh-token' created?"
        ) from e

    return TL_Auth(
        uri=tl_auth_uri,
        client_id=tl_client.client_id,
        client_secret=tl_client.client_secret,
        access_token=SecretStr(access_token_block.get()),
        refresh_token=SecretStr(refresh_token_block.get()),
    )


# def connect_database():
#     return psycopg2.connect(
#         user=os.environ["POSTGRES_USERNAME"],
#         password=os.environ["POSTGRES_PASSWORD"],
#         host=os.environ["POSTGRES_HOST"],
#         port=os.environ["POSTGRES_PORT"],
#         dbname=os.environ["POSTGRES_DATABASE"],
#     )


###############
# Main script #
###############

"""
The user is immediatly redirected to the Teamleader authorization page on server startup.
If the user grands authorization, Teamleader will redirect the user to a route
which will request a access token and save it to the etl_harvest database.  

See https://developer.teamleader.eu/#/introduction/authentication for more info around authorization.
"""


global_state = {}


@asynccontextmanager
async def lifespan(_: FastAPI):
    global_state["state"] = await get_random_state()
    await open_authorization_url(global_state["state"])
    yield


app = FastAPI(lifespan=lifespan)


@app.get("/oauth")
async def authorize(
    code: Optional[str] = None,
    state: Optional[str] = None,
    error: Optional[str] = None,
):

    if error is not None:
        raise PermissionError(error)

    if code is None or state is None:
        return {"error": "Either code or state was not given."}

    if state != global_state["state"]:
        return {
            "error": "The state generated by this server and state returned from Teamleader do not match which might indicate tampering."
        }

    try:
        tokens = await get_access_token_from_teamleader(code)
        # conn = connect_database()
        auth = TL_Auth(
            uri="https://focus.teamleader.eu/oauth2",
            client_id= (await String.load("teamleader-client-id")).value,
            client_secret=(await Secret.load("teamleader-client-secret")).get(),
            refresh_token=tokens["refresh_token"],
            access_token=tokens["access_token"],
        )
        # save_tokens_to_database(auth, conn)
        await save_tokens_to_prefect(auth)
    except (ConnectionError, RuntimeError, ValueError) as e:
        return {"error": str(e)}

    print("\n\nSucces - fetched tokens from Teamleader and saved to prefect\n")
    os.kill(os.getpid(), signal.SIGTERM)
    return {"message": "Succes - fetched tokens from Teamleader and saved to prefect"}


if __name__ == "__main__":

    import subprocess

    import uvicorn

    # Generate a certificate so that the local server can be served with HTTPS.
    if not os.path.exists("key.pem") or not os.path.exists("cert.pem"):
        subprocess.run(
            [
                "openssl",
                "req",
                "-x509",
                "-newkey",
                "rsa:4096",
                "-keyout",
                "key.pem",
                "-out",
                "cert.pem",
                "-sha256",
                "-days",
                "365",
                "-nodes",
                "-subj",
                "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname",
            ],
            check=False,
        )

    uvicorn.run(
        "__main__:app",
        host="127.0.0.1",
        port=8000,
        ssl_certfile="cert.pem",
        ssl_keyfile="key.pem",
    )
